
moto_gpt_config_path: "/workspace/Moto/moto_gpt/configs/models/actPredFalse_motionPredTrue_visionMaeLarge_seq2_chunk5_maskProb0.5.yaml"
latent_motion_tokenizer_path: "/workspace/Moto/latent_motion_tokenizer/checkpoints/latent_motion_tokenizer_trained_on_calvin"
dataset_config_path: "/workspace/Moto/moto_gpt/configs/data/calvin.yaml"
dataloader_config:
  bs_per_gpu: 8
  workers_per_gpu: 2
  prefetch_factor: 2
rgb_preprocessor_config: 
  model_vision_type: "mae"
  vision_aug_config: 
    do_random_resized_crop: false
    do_random_shift: true
training_config:
  num_epochs: 5
  num_warmup_epochs: 1
  print_steps: 100
  lr_max: 0.0001
  weight_decay: 0.0001
  gradient_accumulation_steps: 4
  save_epochs: 1
  save_steps: 10000
  save_path: "/workspace/Moto/moto_gpt/outputs/moto_gpt_pretrained_on_calvin/data_calvin-model_actPredFalse_motionPredTrue_visionMaeLarge_seq2_chunk5_maskProb0.5-train_lr0.0001_bs512-aug_shiftTrue_resizedCropFalse"
  resume_ckpt_path: null
  max_epoch: 3
  pred_binary_gripper_action: true